# DEFINING THE QUESTION

### a) Specifying the Question

This week's project requires us to implement Naive Bayes classifier and calculate the resulting metrics: We will be trying to Determine the Spam Email

---

## b) Defining the Metric for Success

Being able to accurately predict SPAMs.

---

## c) Understanding the context

The last column of 'spambase.data' denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. Most of the attributes indicate whether a particular word or character was frequently occuring in the e-mail. The run-length attributes (55-57) measure the length of sequences of consecutive capital letters. Here are the definitions of the attributes:

48 continuous real [0,100] attributes of type word_freq_WORD
= percentage of words in the e-mail that match WORD, i.e. 100 * (number of times the WORD appears in the e-mail) / total number of words in e-mail. A "word" in this case is any string of alphanumeric characters bounded by non-alphanumeric characters or end-of-string.

6 continuous real [0,100] attributes of type char_freq_CHAR]
= percentage of characters in the e-mail that match CHAR, i.e. 100 * (number of CHAR occurences) / total characters in e-mail

1 continuous real [1,...] attribute of type capital_run_length_average
= average length of uninterrupted sequences of capital letters

1 continuous integer [1,...] attribute of type capital_run_length_longest
= length of longest uninterrupted sequence of capital letters

1 continuous integer [1,...] attribute of type capital_run_length_total
= sum of length of uninterrupted sequences of capital letters
= total number of capital letters in the e-mail

1 nominal {0,1} class attribute of type spam
= denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail.

---

## d) Experimental Design
1. Read and explore the given dataset.

2. Find and deal with outliers, anomalies, and missing data within the dataset.

3. Perform Exploratory Data Analysis.

4. Perforn Naive Bayes Classification.

5. Provide a recommendation based on your analysis.

6. Challenge your solution by providing insights on how you can make improvements in model improvement.

---

## e) Data Relevance

The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...

This collection of spam e-mails came from the collector's postmaster and individuals who had filed spam. The collection of non-spam e-mails came from filed work and personal e-mails, and hence the word 'george' and the area code '650' are indicators of non-spam. These are useful when constructing a personalized spam filter. One would either have to blind such non-spam indicators or get a very wide collection of non-spam to generate a general purpose spam filter.

---


# DATA PREPARATION

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.read_csv('/content/spambase.data', header=None)

0     1     2    3     4     5   ...     52     53     54   55    56  57
0     0.00  0.64  0.64  0.0  0.32  0.00  ...  0.000  0.000  3.756   61   278   1
1     0.21  0.28  0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028   1
2     0.06  0.00  0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259   1
3     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1
4     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1
...    ...   ...   ...  ...   ...   ...  ...    ...    ...    ...  ...   ...  ..
4596  0.31  0.00  0.62  0.0  0.00  0.31  ...  0.000  0.000  1.142    3    88   0
4597  0.00  0.00  0.00  0.0  0.00  0.00  ...  0.000  0.000  1.555    4    14   0
4598  0.30  0.00  0.30  0.0  0.00  0.00  ...  0.000  0.000  1.404    6   118   0
4599  0.96  0.00  0.00  0.0  0.32  0.00  ...  0.000  0.000  1.147    5    78   0
4600  0.00  0.00  0.65  0.0  0.00  0.00  ...  0.000  0.000  1.250    5    40   0

[4601 rows x 58 columns]

In [3]:
pd.read_csv('/content/spambase.names', sep='delimiter', header= None)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


0
0   | SPAM E-MAIL DATABASE ATTRIBUTES (in .names f...
1                                                   |
2   | 48 continuous real [0,100] attributes of typ...
3   | = percentage of words in the e-mail that mat...
4   | i.e. 100 * (number of times the WORD appears...
..                                                ...
82                char_freq_$:            continuous.
83                char_freq_#:            continuous.
84            capital_run_length_average: continuous.
85            capital_run_length_longest: continuous.
86            capital_run_length_total:   continuous.

[87 rows x 1 columns]

In [4]:
pd.read_csv('/content/spambase.DOCUMENTATION', sep='delimiter', header= None)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


0
0                      1. Title:  SPAM E-mail Database
1                                          2. Sources:
2    (a) Creators: Mark Hopkins, Erik Reeber, Georg...
3    Hewlett-Packard Labs, 1501 Page Mill Rd., Palo...
4    (b) Donor: George Forman (gforman at nospam hp...
..                                                 ...
117              56 1    9989   52.173    194.89   374
118              57 1    15841  283.29    606.35   214
119              58 0    1      0.39404   0.4887   124
120  This file: 'spambase.DOCUMENTATION' at the UCI...
121   http://www.ics.uci.edu/~mlearn/MLRepository.html

[122 rows x 1 columns]

In [5]:
# Alternative reading of data

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data

--2021-03-05 08:08:48--  https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 702942 (686K) [application/x-httpd-php]
Saving to: ‘spambase.data.1’

spambase.data.1     100%[===================>] 686.47K  --.-KB/s    in 0.06s   

2021-03-05 08:08:49 (11.6 MB/s) - ‘spambase.data.1’ saved [702942/702942]



In [6]:
group_name = 'spam'

# Loads the CSV data
df = pd.read_csv('spambase.data', header=None)
df

0     1     2    3     4     5   ...     52     53     54   55    56  57
0     0.00  0.64  0.64  0.0  0.32  0.00  ...  0.000  0.000  3.756   61   278   1
1     0.21  0.28  0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028   1
2     0.06  0.00  0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259   1
3     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1
4     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1
...    ...   ...   ...  ...   ...   ...  ...    ...    ...    ...  ...   ...  ..
4596  0.31  0.00  0.62  0.0  0.00  0.31  ...  0.000  0.000  1.142    3    88   0
4597  0.00  0.00  0.00  0.0  0.00  0.00  ...  0.000  0.000  1.555    4    14   0
4598  0.30  0.00  0.30  0.0  0.00  0.00  ...  0.000  0.000  1.404    6   118   0
4599  0.96  0.00  0.00  0.0  0.32  0.00  ...  0.000  0.000  1.147    5    78   0
4600  0.00  0.00  0.65  0.0  0.00  0.00  ...  0.000  0.000  1.250    5    40   0

[4601 rows x 58 columns]

In [7]:
df.head()

0     1     2    3     4     5   ...     52     53     54   55    56  57
0  0.00  0.64  0.64  0.0  0.32  0.00  ...  0.000  0.000  3.756   61   278   1
1  0.21  0.28  0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028   1
2  0.06  0.00  0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259   1
3  0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1
4  0.00  0.00  0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191   1

[5 rows x 58 columns]

In [8]:
df.tail()

0    1     2    3     4     5   ...   52   53     54  55   56  57
4596  0.31  0.0  0.62  0.0  0.00  0.31  ...  0.0  0.0  1.142   3   88   0
4597  0.00  0.0  0.00  0.0  0.00  0.00  ...  0.0  0.0  1.555   4   14   0
4598  0.30  0.0  0.30  0.0  0.00  0.00  ...  0.0  0.0  1.404   6  118   0
4599  0.96  0.0  0.00  0.0  0.32  0.00  ...  0.0  0.0  1.147   5   78   0
4600  0.00  0.0  0.65  0.0  0.00  0.00  ...  0.0  0.0  1.250   5   40   0

[5 rows x 58 columns]

In [9]:
df.shape

(4601, 58)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  

# DATA CLEANING

In [11]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
55    0
56    0
57    0
dtype: int64

The Dataset is clean

---

# DATA ANALYSIS

In [12]:
df.corr()

0         1         2   ...        55        56        57
0   1.000000 -0.016759  0.065627  ...  0.061382  0.089165  0.126208
1  -0.016759  1.000000 -0.033526  ...  0.000271 -0.022680 -0.030224
2   0.065627 -0.033526  1.000000  ...  0.107463  0.070114  0.196988
3   0.013273 -0.006923 -0.020246  ...  0.022081  0.021369  0.057371
4   0.023119 -0.023760  0.077734  ...  0.052290  0.002492  0.241920
5   0.059674 -0.024840  0.087564  ...  0.090172  0.082089  0.232604
6   0.007669  0.003918  0.036677  ...  0.059677 -0.008344  0.332117
7  -0.003950 -0.016280  0.012003  ...  0.037575  0.040252  0.206808
8   0.106263 -0.003826  0.093786  ...  0.189247  0.248724  0.231551
9   0.041198  0.032962  0.032075  ...  0.103308  0.087273  0.138962
10  0.188459 -0.006864  0.048254  ...  0.086791  0.115055  0.234529
11  0.105801 -0.040398  0.083210  ...  0.021774  0.020076  0.007741
12  0.066438 -0.018858  0.047593  ...  0.041962  0.105150  0.132927
13  0.036780 -0.009206  0.008552  ...  0.060993  0.169257  0.060027
14  0.028439  0.005330  0.122113  ...  0.213992  0.151626  0.195902
15  0.059386 -0.009117  0.063906  ...  0.026528  0.003007  0.263215
16  0.081928 -0.018370  0.036262  ...  0.062672  0.064261  0.263204
17  0.053324  0.033500  0.121923  ...  0.075122  0.046364  0.204208
18  0.128243 -0.055476  0.139329  ...  0.006530 -0.007307  0.273651
19  0.021295 -0.015806  0.031111  ...  0.099463  0.075751  0.189761
20  0.197049 -0.018191  0.156651  ...  0.085321  0.051797  0.383234
21 -0.024349 -0.008850 -0.035681  ...  0.027775  0.103954  0.091860
22  0.134072 -0.020502  0.123671  ...  0.123036  0.165977  0.334787
23  0.188155  0.001984  0.041145  ...  0.044870  0.080993  0.216111
24 -0.072504 -0.043483 -0.087924  ... -0.051206 -0.043267 -0.256723
25 -0.061686 -0.038211 -0.062459  ... -0.051806 -0.059601 -0.232968
26 -0.066424 -0.030307 -0.108886  ... -0.054400 -0.096548 -0.183404
27 -0.048680 -0.029221 -0.050648  ... -0.038772 -0.067596 -0.158800
28 -0.041251 -0.021940 -0.057726  ... -0.034733 -0.056628 -0.133523
29 -0.052799 -0.027508 -0.032547  ... -0.039001 -0.064115 -0.171095
30 -0.039066 -0.018097 -0.038927  ... -0.027449 -0.045923 -0.126912
31 -0.032058 -0.003326 -0.061870  ... -0.027732 -0.046796 -0.114214
32 -0.041014 -0.024903 -0.054759  ... -0.025919  0.006919 -0.119931
33 -0.027690 -0.004303 -0.061706  ... -0.024532 -0.044529 -0.112754
34 -0.044954 -0.024058 -0.048335  ... -0.030236 -0.045963 -0.149225
35 -0.054673 -0.028198 -0.046504  ... -0.038100 -0.045792 -0.136134
36 -0.057312 -0.024013 -0.067015  ... -0.033204 -0.003490 -0.178045
37 -0.007960 -0.008922  0.032407  ... -0.009487 -0.013897 -0.031035
38 -0.011134 -0.019124 -0.014809  ... -0.029229 -0.049256 -0.122831
39 -0.036095 -0.014821 -0.047066  ... -0.004835 -0.028806 -0.064801
40 -0.009703 -0.015420 -0.030956  ... -0.023658 -0.026373 -0.097375
41 -0.026070 -0.025177 -0.005811  ... -0.034585 -0.056511 -0.136615
42 -0.024292 -0.002370 -0.044325  ... -0.017279 -0.036529 -0.135664
43 -0.022116 -0.019739 -0.053464  ... -0.025918 -0.040661 -0.094594
44 -0.037105 -0.016418 -0.050664  ... -0.051858 -0.095444 -0.140408
45 -0.034056 -0.023858 -0.056655  ... -0.033365 -0.046371 -0.146138
46 -0.000953 -0.009818  0.029339  ... -0.010154  0.005158 -0.044679
47 -0.017755 -0.015747 -0.026344  ... -0.016894 -0.010033 -0.084020
48 -0.026505 -0.007282 -0.033213  ...  0.040829  0.055298 -0.059630
49 -0.021196 -0.049837 -0.016495  ...  0.370963  0.112209 -0.089672
50 -0.033301 -0.018527 -0.033120  ... -0.013994  0.006016 -0.064709
51  0.058292 -0.014461  0.108140  ...  0.077392  0.036321  0.241888
52  0.117419 -0.009605  0.087618  ...  0.183144  0.201948  0.323629
53 -0.008844  0.001946 -0.003336  ...  0.061657  0.042568  0.065067
54  0.044491  0.002083  0.097398  ...  0.492638  0.162314  0.109999
55  0.061382  0.000271  0.107463  ...  1.000000  0.475486  0.216097
56  0.089165 -0.022680  0.070114  ...  0.475486  1.000000  0.249164
57  0.126208 -0.030224  0.196988  ...  0.216097  0.249164  1.00000

# MODELING

## PREPARATION

In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = df.loc[:, 0:56]
y = df.loc[:,57]

## 80:20 Model 

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.20, random_state= 10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
gaus = GaussianNB()

gaus.fit(X_train, y_train)

y_pred = gaus.predict(X_test)

print('Accuracy Score is: ', accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score is:  0.8273615635179153
[[407 152]
 [  7 355]]
              precision    recall  f1-score   support

           0       0.98      0.73      0.84       559
           1       0.70      0.98      0.82       362

    accuracy                           0.83       921
   macro avg       0.84      0.85      0.83       921
weighted avg       0.87      0.83      0.83       921



## 70:30 Model

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.30, random_state= 10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
gaus = GaussianNB()

gaus.fit(X_train, y_train)

y_pred = gaus.predict(X_test)

print('Accuracy Score is: ', accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score is:  0.8211440984793628
[[595 226]
 [ 21 539]]
              precision    recall  f1-score   support

           0       0.97      0.72      0.83       821
           1       0.70      0.96      0.81       560

    accuracy                           0.82      1381
   macro avg       0.84      0.84      0.82      1381
weighted avg       0.86      0.82      0.82      1381



## 60:40 Model

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.40, random_state= 10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
gaus = GaussianNB()

gaus.fit(X_train, y_train)

y_pred = gaus.predict(X_test)

print('Accuracy Score is: ', accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy Score is:  0.8245518739815317
[[801 289]
 [ 34 717]]
              precision    recall  f1-score   support

           0       0.96      0.73      0.83      1090
           1       0.71      0.95      0.82       751

    accuracy                           0.82      1841
   macro avg       0.84      0.84      0.82      1841
weighted avg       0.86      0.82      0.83      1841



We can notice that as the train split decreases the accuracy scores decrease, indicating the more the data for training, the better the results will be. Therefore, our 80:20 Model split gave the best results.

## OPTIMIZING 80:20 Model

In [22]:
corr_matrix = X.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation greater than 0.80
to_drop = [column for column in upper.columns if any(upper[column] > 0.80)]

# Drop features 
X.drop(X[to_drop], axis=1)

# Seems that no columns are highly correlated

0     1     2    3     4     5   ...     51     52     53     54   55    56
0     0.00  0.64  0.64  0.0  0.32  0.00  ...  0.778  0.000  0.000  3.756   61   278
1     0.21  0.28  0.50  0.0  0.14  0.28  ...  0.372  0.180  0.048  5.114  101  1028
2     0.06  0.00  0.71  0.0  1.23  0.19  ...  0.276  0.184  0.010  9.821  485  2259
3     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.137  0.000  0.000  3.537   40   191
4     0.00  0.00  0.00  0.0  0.63  0.00  ...  0.135  0.000  0.000  3.537   40   191
...    ...   ...   ...  ...   ...   ...  ...    ...    ...    ...    ...  ...   ...
4596  0.31  0.00  0.62  0.0  0.00  0.31  ...  0.000  0.000  0.000  1.142    3    88
4597  0.00  0.00  0.00  0.0  0.00  0.00  ...  0.353  0.000  0.000  1.555    4    14
4598  0.30  0.00  0.30  0.0  0.00  0.00  ...  0.000  0.000  0.000  1.404    6   118
4599  0.96  0.00  0.00  0.0  0.32  0.00  ...  0.000  0.000  0.000  1.147    5    78
4600  0.00  0.00  0.65  0.0  0.00  0.00  ...  0.125  0.000  0.000  1.250    5    40

[4601 rows x 55 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.20, random_state= 10)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
# To try improve the scores, we could try and improve the imbalance of the classes as
# indicated by the lower support values of class 1 in all models.

# import library
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

ros = RandomOverSampler(random_state=42)

# fit predictor and target variablex_ros, 

x_ros, y_ros = ros.fit_resample(X, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_ros))

Original dataset shape Counter({0: 2788, 1: 1813})
Resample dataset shape Counter({1: 2788, 0: 2788})


/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [25]:
X_train, X_test, y_train, y_test = train_test_split(x_ros, y_ros, test_size=0.20, random_state= 10)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
gaus = GaussianNB()

gaus.fit(X_train, y_train)

y_pred = gaus.predict(X_test)

print('Accuracy Score is: ', accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# The f1- scores have slightly improved, possibly due to the improved class balance as shown by 
# the support values

Accuracy Score is:  0.8449820788530465
[[398 148]
 [ 25 545]]
              precision    recall  f1-score   support

           0       0.94      0.73      0.82       546
           1       0.79      0.96      0.86       570

    accuracy                           0.84      1116
   macro avg       0.86      0.84      0.84      1116
weighted avg       0.86      0.84      0.84      1116



# CONCLUSION

The precision informs us on the accuracy of the true positive predictions with regards to false positives. The recall informs us on the accuracy of the true positive predictions with regards to false negatives. The f1-score finds the best balance between precision and recall. For this challenge the best accuracy score to work with, in order to beat the accuracy paradox of the accuracy score is the f1-score. Using this, the 80:20 split Model is the best Model.

---

# CHALLENGING THE SOLUTION

In [27]:
# Using Multinomial

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=69)

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [28]:
from sklearn.model_selection import GridSearchCV

alpha = np.logspace(0,10,20)
hyperparams = dict(alpha = alpha)

clf = GridSearchCV(model, hyperparams, cv=5)

best_model = clf.fit(X_train, y_train)

In [29]:
# Viewing best hyperparameters
print('Best alpha:', best_model.best_estimator_.get_params()['alpha'])
print('Best Class_prior:', best_model.best_estimator_.get_params()['class_prior'])
print('Best Fit_prior:', best_model.best_estimator_.get_params()['fit_prior'])

# the best hyperparameters are similar to the basic model.

Best alpha: 1.0
Best Class_prior: None
Best Fit_prior: True


In [30]:
y_pred = model.predict(X_test)

print('Accuracy Score is: ', accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# The values are lower, showing that our best model was the Gauss NB.

Accuracy Score is:  0.7722342733188721
[[230  55]
 [ 50 126]]
              precision    recall  f1-score   support

           0       0.82      0.81      0.81       285
           1       0.70      0.72      0.71       176

    accuracy                           0.77       461
   macro avg       0.76      0.76      0.76       461
weighted avg       0.77      0.77      0.77       461



# RECOMMENDATION

Our Gaussian method gave the best better f1-score values. The dataset however should have been provided with better column names in order to know what each feature represents.

---

# FOLLOW UP QUESTIONS

## a) Did we have the right data?

No, we do not know what all the features represent

## b) Do we need other data to answer our question?

Yes, we need column names in order to know what each feature represents.

## c) Did we have the right question?

Yes, because SPAM emails have led to many scams.